tasks/urls.py
from django.urls import path

from . import views

#задаем namespace
app_name = "tasks"

urlpatterns = [
    path('', views.index, name='index'),
    # path('list/', views.tasks_list, name='list'), данные пути убираем, т.к. убрали функции-обработчики и заменили классами-обработчиками
    # path("create/", views.task_create, name="create"),
    # path("add-task/", views.add_task, name="api-add-task"), не нужен путь, т.к. убрали обработчик add_task
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    #прописываем пути для классо обработчиков
    #path("list/", views.TaskListView.as_view(), name="list"),
    path("list/", views.tasks_by_tag, name="list"),
    path("list/tag/<slug:tag_slug>", views.tasks_by_tag, name="list_by_tag"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),
    path("edit/<int:pk>", views.TaskEditView.as_view(), name="edit"),
    path("export/", views.TaskExportView.as_view(), name="export"),
]

todoapp/urls.py
from django.contrib.auth import views as auth_views
"""todoapp URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

app_name = "tasks"

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(), name='login'),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_1OOT)

tasks/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from todoapp.ru_taggit import RuTaggedItem


class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Высокий приоритет"),
        (PRIORITY_MEDIUM, "Средний приоритет"),
        (PRIORITY_LOW, "Низкий приоритет"),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tasks")
    priority = models.IntegerField(
        "Приоритет", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )
    #добавление тэгов
    tags = TaggableManager()
    tags = TaggableManager(through=RuTaggedItem)

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ('-created',)

    #получаем абсолютный адрес. В админке автоматичкски включается ссылка на задачу
    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])

tasks/forms.py
from django import forms

from tasks.models import TodoItem

#генерация формы для заполнения
# class AddTaskForm(forms.Form):
#     description = forms.CharField(max_length=64, label="")

#модельная форма, связвается с моделью TodoItem
class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ("description", "priority", "tags")
        labels = {"description": "Описание", "priority": "", "tags": "тэги"}

class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label="высокая важность", initial=True, required=False
    )
    prio_med = forms.BooleanField(
        label="средней важности", initial=True, required=False
    )
    prio_low = forms.BooleanField(
        label="низкой важности", initial=False, required=False
    )

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from tasks.models import TodoItem
from tasks.forms import  TodoItemForm, TodoItemExportForm

#импортируем классы обработчики
from django.views import View
from django.views.generic import ListView

#3. импортируем модуль для работы с именами путей, вместо самих путей
from django.urls import reverse

#4. Импорт класса для отображения деталей задачи
from django.views.generic.detail import DetailView

#5. Добавляем требование авторизации
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Q

from django.views import View

from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from . import service
from taggit.models import Tag, TaggedItem





#5
@login_required
def index(request):
    return HttpResponse("Примитивный ответ из приложения tasks")

def complete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    return HttpResponse("OK")


def delete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.delete()
    #3.return redirect("/tasks/list")    
    return redirect(reverse("tasks:list"))


#2. заменяем функцию обработчик на класс обработчик     
# def task_create(request):
#     if request.method == "POST":
#         form = TodoItemForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("/tasks/list")
#     else:
#         form = TodoItemForm()

#     return render(request, "tasks/create.html", {"form": form})

class TaskCreateView(View):
    def my_render(self, request, form):
        return render(request, "tasks/create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            # form.save()
            # return redirect("tasks:list")
            #добавляем владельца задачи
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            form.save_m2m()
            return redirect(reverse("tasks:list"))

        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return self.my_render(request, form)

# 1. больше не нужно, т.к. вынесли логику POST (создания задачи) в "обработчик" (функцию) task_create
# def add_task(request):
#     if request.method == "POST":
#         desc = request.POST["description"]
#         t = TodoItem(description=desc)
#         t.save()
#     return redirect("/tasks/list")
   
# 2. заменяем функцию обработчик на класс обработчик 
# def tasks_list(request):
#     all_tasks = TodoItem.objects.all()
#     return render(
#         request,
#         'tasks/list.html',
#         {'tasks': all_tasks}
#     )

class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"
    
    #первый способ получения всех тасок юзера
    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     u = self.request.user
    #     if u.is_anonymous:
    #         return []
    #     return qs.filter(owner=u)
    #второй способ получения всех тасок юзера через "обратное отношение" которое было задано у модели
    def get_queryset(self):
        u = self.request.user
        #ниже строчки убрали, т.к. подмешали класс по проверке валидации пользователя
        # if u.is_anonymous:
        #     return []
        return u.tasks.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        user_tasks = self.get_queryset()
        
        tags = []
        
        for t in user_tasks:
            tags.append(list(t.tags.all()))
        
        context['tags'] = service.filter_tags(tags)
        
        return context

#4.
class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'

class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect(reverse("tasks:list"))

        return render(request, "tasks/edit.html", {"form": form, "task": t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, "tasks/edit.html", {"form": form, "task": t})

class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities["prio_high"]:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = "Ваши задачи и приоритеты:\n"
        for t in list(tasks):
            if t.is_completed:
                body += f"[x] {t.description} ({t.get_priority_display()})\n"
            else:
                body += f"[ ] {t.description} ({t.get_priority_display()})\n"

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Задачи", body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, "Задачи были отправлены на почту %s" % email)
        else:
            messages.error(request, "Что-то пошло не так, попробуйте ещё раз")
        return redirect(reverse("tasks:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "tasks/export.html", {"form": form})

def tasks_by_tag(request, tag_slug=None):
    u = request.user
    tasks = TodoItem.objects.filter(owner=u).all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        tasks = tasks.filter(tags__in=[tag])
    
    all_tags = []
    for t in tasks:
        all_tags.append(list(t.tags.all()))
    all_tags = service.filter_tags(all_tags)

    return render(
        request,
        "tasks/list_by_tag.html",
        {"tag": tag, "tasks": tasks, "all_tags": all_tags},
    )

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Создать задачу{% endblock %}

{% block main_content %}
  <h1>Создать задачу</h1>
   <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Добавить</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задача {{ object.id }}{% endblock %}
{% block extra_head %}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"

{% endblock %}

{% block main_content %}
  <h1>Задача</h1>
  <p><b>Описание</b>: {{ object }}</p>
  <ul>
    <li>
   <!--  {% if object.is_completed %}
        Задача выполнена
    {% else %}
        Задача ещё не выполнена
    {% endif %} -->
    <!-- заменяем конструкцию if/else на одну строчку -->
    {{ object.is_completed|yesno:"Задача выполнена, Задача ещё не выполнена" }}
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: {{ object.created|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: {{ object.updated }}</li>
    <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "tasks:edit" pk=object.pk %}">Редактировать</a></li>
  </ul>
  <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "tasks:list" %}">Назад к списку</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block title %}Изменить задачу{% endblock %}

{% block main_content %}
  <h1>Поменять задачу</h1>
  <form action="{% url "tasks:edit" task.pk %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Сохранить</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/export.html
{% extends "base.html" %}

{% block title %}Экспорт{% endblock %}

{% block main_content %}
  <h1>Экспорт задач</h1>
  <p>На вашу почту придёт емейл с задачами. Уточните список.</p>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Жмяк</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block main_content %}
  <h1>Текущие задачи</h1>
  <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">экспорт</a></h1>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li>
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' />
    {% endif %}
      {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <a class="remove" href={% url "tasks:delete" task.id %}>X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %}

tasks/templates/tasks/list_by_tag.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block main_content %}
  {% if tag %}
  <h1>Текущие задачи с тэгом "{{ tag.name }}"</h1>
  {% else %}
  <h1>Все текущие задачи</h1>
  {% endif %}
 
  <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">экспорт</a></p>
  {% for t in all_tags %}
    {% if forloop.first %}<ul class="list-inline">
        <li class="list-inline-item">тэги:</li>
    {% endif %}
    <li class="list-inline-item">
      <a href="{% url "tasks:list_by_tag" t.slug %}">
      {% if t.pk == tag.pk %}
        <span class="badge badge-success">{{ t.name }}</span>
      {% else %}
        <span class="badge badge-info">{{ t.name }}</span>
      {% endif %}
      </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}
 
  <hr/>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li>
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' />
    {% endif %}
      {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <a class="remove" href={% url "tasks:delete" task.id %}>X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %} )